apiVersion: v1beta1
appVersion: 0.6
description: CRDs for EnRoute API Gateway
home: https://getenroute.io/
icon: https://getenroute.io/favicon.ico
keywords:
 - api gateway
 - EnRoute - Envoy Route Controller
 - Saaras
 - envoy
 - ingress
maintainers:
 - email: contact@saaras.io
   name: contact
name: enroute-crds
sources:
 - https://github.com/saarasio/enroute
 - https://getenroute.io
 - https://github.com/envoyproxy/envoy
version: 0.2.0
