apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalconfigs.enroute.saaras.io
  labels:
    component: globalconfig
spec:
  group: enroute.saaras.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: globalconfigs
    kind: GlobalConfig

