apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routefilters.enroute.saaras.io
  labels:
    component: routefilter
spec:
  group: enroute.saaras.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: routefilters
    kind: RouteFilter

