{{- if .Values.filters.virtualhost.lua.enable -}}
apiVersion: enroute.saaras.io/v1
kind: HttpFilter
metadata:
  labels:
    component: lua
    configscope: vhconfig
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-luafilter
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-{{ .Values.service.port }}-luafilter
  type: vh_filter_lua
  httpFilterConfig:
    config: |
        function envoy_on_request(request_handle)
           request_handle:logInfo("Hello World request");
        end
        
        function envoy_on_response(response_handle)
           response_handle:logInfo("Hello World response VH");
           response_handle:headers():add("Lua-Filter-Says-VH", "Hello Lua VH")
        end

{{- end -}}
