definitions:
  webhttp.Proxy:
    properties:
      name:
        type: string
    type: object
  webhttp.Route:
    properties:
      route_name:
        type: string
      route_prefix:
        type: string
    type: object
  webhttp.Service:
    properties:
      fqdn:
        type: string
      service_name:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://saaras.io/
  description: APIs to configure multiple envoy proxies
  license: {}
  title: Enroute API
  version: "1.0"
paths:
  /proxy:
    get:
      consumes:
      - application/json
      description: Get a list of all proxies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: List proxies
      tags:
      - proxy
    post:
      consumes:
      - application/json
      description: Create a proxy
      parameters:
      - description: Name of proxy to create
        in: body
        name: Name
        required: true
        schema:
          $ref: '#/definitions/webhttp.Proxy'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: Create a proxy
      tags:
      - proxy
  /proxy/{proxy_name}:
    delete:
      consumes:
      - application/json
      description: Delete a proxy
      parameters:
      - description: Name of proxy to delete
        in: path
        name: proxy_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Delete a proxy
      tags:
      - proxy
  /proxy/{proxy_name}/service:
    get:
      consumes:
      - application/json
      description: Get all services associated with a proxy
      parameters:
      - description: Name of proxy for which to list services
        in: path
        name: proxy_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: List services associated with proxy
      tags:
      - proxy
  /proxy/{proxy_name}/service/{service_name}:
    delete:
      consumes:
      - application/json
      description: Disassociate a service from proxy
      parameters:
      - description: Name of proxy for which to list service
        in: path
        name: proxy_name
        required: true
        type: string
      - description: Name of service to list
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Disassociate a service from proxy
      tags:
      - proxy
    get:
      consumes:
      - application/json
      description: Return specified service associated with this proxy
      parameters:
      - description: Name of proxy for which to list service
        in: path
        name: proxy_name
        required: true
        type: string
      - description: Name of service to list
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Return specified service associated with this proxy
      tags:
      - proxy
    post:
      consumes:
      - application/json
      description: Associate a service with proxy
      parameters:
      - description: Name of proxy for which to list service
        in: path
        name: proxy_name
        required: true
        type: string
      - description: Name of service to list
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Associate a service with proxy
      tags:
      - proxy
  /proxy/dump:
    get:
      consumes:
      - application/json
      description: Get a detailed version of list of proxies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Get all proxy details
      tags:
      - proxy
  /proxy/dump/{proxy_name}:
    get:
      consumes:
      - application/json
      description: Get a detailed version of specified proxy
      parameters:
      - description: Name of proxy for which to list services
        in: path
        name: proxy_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Get details of specified proxy
      tags:
      - proxy
  /service:
    get:
      consumes:
      - application/json
      description: Get a list of all services for all proxies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: List all services
      tags:
      - service
    post:
      consumes:
      - application/json
      description: Create a service
      parameters:
      - description: Service to create
        in: body
        name: Service
        required: true
        schema:
          $ref: '#/definitions/webhttp.Service'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: Create a service
      tags:
      - service
  /service/{service_name}:
    delete:
      consumes:
      - application/json
      description: Delete specified service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Delete the specified service
      tags:
      - service
    get:
      consumes:
      - application/json
      description: Fetch some details of specified service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Fetch some details of specified service
      tags:
      - service
    patch:
      consumes:
      - application/json
      description: Update a service
      parameters:
      - description: Fields of service to update
        in: body
        name: Service
        required: true
        schema:
          $ref: '#/definitions/webhttp.Service'
          type: object
      - description: name of service to update
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: Update a service
      tags:
      - service
  /service/{service_name}/proxy:
    get:
      consumes:
      - application/json
      description: Fetch list of proxies on which this service is programmed
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Fetch list of proxies on which this service is programmed
      tags:
      - service
      - proxy
  /service/{service_name}/route:
    get:
      consumes:
      - application/json
      description: Get all routes for a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Get all routes for a service
      tags:
      - service
      - route
    post:
      consumes:
      - application/json
      description: Create a route associated with a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Route to create
        in: body
        name: Route
        required: true
        schema:
          $ref: '#/definitions/webhttp.Route'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Create a route associated with a service
      tags:
      - service
      - route
  /service/{service_name}/route/{route_name}:
    get:
      consumes:
      - application/json
      description: Delete the route associated with the service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of route to delete
        in: path
        name: route_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Delete the route associated with the service
      tags:
      - service
      - route
    patch:
      consumes:
      - application/json
      description: Update a route associated with a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of service
        in: path
        name: route_name
        required: true
        type: string
      - description: Route to update
        in: body
        name: Route
        required: true
        schema:
          $ref: '#/definitions/webhttp.Route'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Update a route associated with a service
      tags:
      - service
      - route
  /service/{service_name}/route/{route_name}/upstream:
    get:
      consumes:
      - application/json
      description: Get all upstreams associated with a service route
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of route
        in: path
        name: route_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Get all upstreams associated with a service route
      tags:
      - service
      - route
      - upstream
  /service/{service_name}/route/{route_name}/upstream/{upstream_name}:
    get:
      consumes:
      - application/json
      description: Disassociate an upstream with a service route. This does not delete
        the upstream.
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of route
        in: path
        name: route_name
        required: true
        type: string
      - description: Name of upstream to disassociate with service route
        in: path
        name: upstream_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Disassociate an upstream with a service route
      tags:
      - service
      - route
      - upstream
  /service/{service_name}/secret:
    get:
      consumes:
      - application/json
      description: List all secrets associated with a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: List all secrets associated with a service
      tags:
      - service
      - secret
  /service/{service_name}/secret/{secret_name}:
    delete:
      consumes:
      - application/json
      description: Disassociate a secret with a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of secret
        in: path
        name: secret_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Disassociate a secret with a service
      tags:
      - service
      - secret
    post:
      consumes:
      - application/json
      description: Associate a secret with a service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      - description: Name of secret
        in: path
        name: secret_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Associate a secret with a service
      tags:
      - service
      - secret
  /service/copy/{service_name_src}/{service_name_dst}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Name of service
        in: path
        name: service_name_src
        required: true
        type: string
      - description: Name of service
        in: path
        name: service_name_dst
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Copy service
      tags:
      - service
  /service/copyroute/{service_name_src}/{service_name_dst}/route/{route_name}:
    post:
      consumes:
      - application/json
      description: Copy a route on source service to a destination service
      parameters:
      - description: Name of service
        in: path
        name: service_name_src
        required: true
        type: string
      - description: Name of service
        in: path
        name: service_name_dst
        required: true
        type: string
      - description: Name of service
        in: path
        name: route_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Copy a route on source service to a destination service
      tags:
      - service
      - route
  /service/deepcopy/{service_name_src}/{service_name_dst}:
    post:
      consumes:
      - application/json
      description: Deep copy service copies service, associated routes and upstream
        associations. Upstream copies are not created.
      parameters:
      - description: Name of service
        in: path
        name: service_name_src
        required: true
        type: string
      - description: Name of service
        in: path
        name: service_name_dst
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Deep copy service
      tags:
      - service
      - route
  /service/dump/{service_name}:
    get:
      consumes:
      - application/json
      description: Fetch detail of specified service
      parameters:
      - description: Name of service
        in: path
        name: service_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Fetch detail of specified service
      tags:
      - service
swagger: "2.0"
