info:
  contact:
    name: API Support
    url: https://saaras.io/
  description: Provide API to configure multiple envoy proxies
  license: {}
  title: Enroute API
  version: "1.0"
paths:
  /proxy:
    get:
      consumes:
      - application/json
      description: Get a list of all proxies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: List proxies
      tags:
      - proxy
swagger: "2.0"
