apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalconfigs.enroute.saaras.io
  labels:
    component: globalconfig
spec:
  group: enroute.saaras.io
  scope: Namespaced
  names:
    plural: globalconfigs
    kind: GlobalConfig
    listKind: GlobalConfigList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: GlobalConfig CRD
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: defines the spec of the CRD
              type: object
              properties:
                name:
                  type: string
                  description: name of the globalconfig
                type:
                   type: string
                   description: globalconfig type
                config:
                  type: string
                  description: config of globalconfig
