apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpfilters.enroute.saaras.io
  labels:
    component: httpfilter
spec:
  group: enroute.saaras.io
  scope: Namespaced
  names:
    plural: httpfilters
    kind: HttpFilter
    listKind: HttpFilterList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: HttpFilter CRD
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: defines the spec of the CRD
              type: object
              properties:
                name:
                  type: string
                  description: name of the filter
                type:
                   type: string
                   description: filter type
                services:
                   type: object
                   description: external service filter talks to
                   properties:
                     name:
                       type: string
                       description: name of the service
                     port:
                       type: integer
                       description: port of the service
                     protocol:
                       type: string
                       description: protocol to use to talk to the service
                httpFilterConfig:
                   type: object
                   description: yaml config for the filter
                   properties:
                     config:
                       type: string
                       description: config of filter
