apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httpfilters.enroute.saaras.io
  labels:
    component: httpfilter
spec:
  group: enroute.saaras.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: httpfilters
    kind: HttpFilter

