apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: enroute-gw-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: enroute-gw-k8s
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: enroute.saaras.io/v1beta1
kind: IngressRoute
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: enroute-gw-k8s
spec:
  virtualhost:
    fqdn: kuard.local
  routes:
    - match: /
      services:
        - name: kuard
          port: 80
      filters:
        - name: rl2
          type: rl
---
apiVersion: enroute.saaras.io/v1beta1
kind: ProxyConfig
metadata:
  labels:
    app: kuard
  name: rl-global-config
  namespace: enroute-gw-k8s
spec:
  name: rl-global-config
  type: rl
  config: |
        domain: "enroute"
        descriptors:
          - key: generic_key
            value: default
            descriptors:
            - key: remote_address
              rate_limit:
                unit: second
                requests_per_unit: 6
          - key: remote_address
            rate_limit:
              unit: second
              requests_per_unit: 0
---
apiVersion: enroute.saaras.io/v1beta1
kind: RouteFilter
metadata:
  labels:
    app: kuard
  name: rl2
  namespace: enroute-gw-k8s
spec:
  name: rl2
  type: rl
  routeFilterConfig:
    config: |
      { 
        "descriptors" : 
        [ 
                {"remote_address": "{}"},
                {"destination_cluster": "{}"} 
        ] 
      }
---
