apiVersion: v1
kind: Service
metadata:
 name: enroute
 namespace: {{ .Values.globalSettings.namespace.name }}
 annotations:
  # This annotation puts the AWS ELB into "TCP" mode so that it does not
  # do HTTP negotiation for HTTPS connections at the ELB edge.
  # The downside of this is the remote IP address of all connections will
  # appear to be the internal address of the ELB. See docs/proxy-proto.md
  # for information about enabling the PROXY protocol on the ELB to recover
  # the original remote IP address.
  
  {{- if .Values.awsSettings.enable -}}
  #
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  service.beta.kubernetes.io/aws-load-balancer-type: nlb
  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  {{- end }}

  {{- if .Values.ociSettings.enable -}}
  #
  service.beta.kubernetes.io/oci-load-balancer-backend-protocol: http
  {{- end }}

  # Scrape metrics for the enroute container
  # The envoy container is scraped by annotations on the pod spec
  prometheus.io/port: "8000"
  prometheus.io/scrape: "true"
spec:
 ports:
 - port: 80
   name: http
   protocol: TCP
   targetPort: 8080
 - port: 443
   name: https
   protocol: TCP
   targetPort: 8443
 selector:
   app: enroute
 externalTrafficPolicy: Local
 type: LoadBalancer
