{{- if eq .Values.service.name "hello-enroute" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-enroute
  namespace: {{ .Values.globalSettings.namespace.name }}
  labels:
    app: hello-enroute
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: 8080
  - name: https
    port: 9091
    targetPort: 8081
  selector:
    app: hello-enroute
---
{{- end }}
