{{- if or (eq .Values.serviceAccount.create true) (eq .Values.enrouteService.rbac.create true) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "enroute.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - "enroute.saaras.io"
    resources:
      - ingresses
      - gatewayhosts
      - globalconfigs
      - httpfilters
      - routefilters
      - tlscertificatedelegations
    verbs:
      - get
      - list
      - watch
      - put
      - post
      - patch
{{- end }}
