{{- if .Values.globalSettings.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enroutedemo
  namespace: enroutedemo
  labels:
    {{- include "enroute.labels" . | nindent 4 }}
  {{- with .Values.globalSettings.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.globalSettings.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enroutedemo
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups: ["enroute.saaras.io"]
  resources: ["ingresses", "gatewayhosts", "globalconfigs", "httpfilters", "routefilters", "tlscertificatedelegations"]
  verbs:
  - get
  - list
  - watch
  - put
  - post
  - patch
{{- end }}
---
{{- if .Values.globalSettings.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enroutedemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enroutedemo
subjects:
- kind: ServiceAccount
  name: enroutedemo
  namespace: enroutedemo
{{- end }}
---
{{- if .Values.globalSettings.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: enroutedemo
{{- end }}
---
