apiVersion: v1
kind: Service
metadata:
  name: {{ include "enroute.fullname" . }}
  labels:
    {{- include "enroute.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "enroute.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
