---
apiVersion: enroute.saaras.io/v1beta1
kind: GatewayHost
metadata:
  labels:
    app: hello-enroute
  name: {{ .Values.service.name }}-gatewayhost-notls
  namespace: enroutedemo
spec:
  virtualhost:
    {{- if .Values.service.fqdn -}}
    #
    fqdn: {{ .Values.service.fqdn }}
    {{- else }}
    fqdn: '*'
    {{- end }}
    #
    {{- if .Values.filters.lua.enable -}}
    #
    filters:
      - name: luatestfilter
        type: http_filter_lua
    {{- end }}
    {{- if .Values.filters.cors.enable -}}
    #
      - name: corsfilter
        type: http_filter_cors
    {{- end }}
    {{- if .Values.filters.jwt.enable -}}
    #
      - name: jwtfilter
        type: http_filter_jwt
    {{- end }}
  routes:
    - conditions:
      - prefix: /
        header:
          name: ":method"
          exact: "GET"
      {{- if .Values.filters.ratelimit.enable -}}
      #
      filters:
        - name: rl2
          type: route_filter_ratelimit
      {{- end }}
      services:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
---
apiVersion: enroute.saaras.io/v1beta1
kind: GlobalConfig
metadata:
  labels:
    app: hello-enroute
  name: rl-global-config
  namespace: enroutedemo
spec:
  name: rl-global-config
  type: globalconfig_ratelimit
  config: |
        {
          "domain": "enroute",
          "descriptors" :
          [
            {
              "key": "x-forwarded-for",
              "descriptors" :
              [
                {
                  "key" : "x-forwarded-proto",
                  "value" : "http",
                  "rate_limit" : { "unit" : "second", "requests_per_unit" : 2 }
                }
              ]
            }
          ]
        }
---
apiVersion: enroute.saaras.io/v1beta1
kind: RouteFilter
metadata:
  labels:
    app: hello-enroute
  name: rl2
  namespace: enroutedemo
spec:
  name: rl2
  type: route_filter_ratelimit
  routeFilterConfig:
    config: |
          { 
            "descriptors" : 
            [ 
              { "request_headers": { "header_name": "x-forwarded-for", "descriptor_key": "x-forwarded-for" } },
              { "request_headers": { "header_name": "x-forwarded-proto", "descriptor_key": "x-forwarded-proto" } }
            ]
          }
---
apiVersion: enroute.saaras.io/v1beta1
kind: HttpFilter
metadata:
  labels:
    app: hello-enroute
  name: luatestfilter
  namespace: enroutedemo
spec:
  name: luatestfilter
  type: http_filter_lua
  httpFilterConfig:
    config: |
        function envoy_on_request(request_handle)
           request_handle:logInfo("Hello World request");
        end

        function envoy_on_response(response_handle)
           response_handle:logInfo("Hello World response");
        end
---
apiVersion: enroute.saaras.io/v1beta1
kind: HttpFilter
metadata:
  labels:
    app: hello-enroute
  name: corsfilter
  namespace: enroutedemo
spec:
  name: corsfilter
  type: http_filter_cors
  httpFilterConfig:
    config: |
         {
             "match_condition" : {
               "regex" : "\\*"
             },
             "access_control_allow_methods" : "GET, OPTIONS",
             "access_control_allow_headers" : "X-PINGOTHER, Content-Type",
             "access_control_expose_headers" : "*",
             "access_control_max_age" : "120"
         }
---
apiVersion: enroute.saaras.io/v1beta1
kind: HttpFilter
metadata:
  labels:
    app: hello-enroute
  name: jwtfilter
  namespace: enroutedemo
spec:
  name: jwtfilter
  type: http_filter_jwt
  services:
     name: externalauth
     port: 443
     protocol: tls
  httpFilterConfig:
    config: |
         {
           "name" : "auth0",
           "jwks_uri" : "https://saaras.auth0.com/.well-known/jwks.json",
           "audience" : "api-identifier",
           "issuer" : "https://saaras.auth0.com/",
           "route" : [{"prefix" : "/"}],
           "jwt_service_name" : "auth0",
           "jwt_service_port" : 443,
           "jwt_forward_header_name" : "x-jwt-token"
         }
---
apiVersion: v1
kind: Service
metadata:
  name: externalauth
  namespace: enroutedemo
spec:
  type: ExternalName
  externalName: saaras.auth0.com
  ports:
  - port: 443
  # important to set protocol name
    name: https
---
