version: '3.6'
services:
  enroute-cp:
    image: gcr.io/enroute-10102020/enroute-cp:latest
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/11/main
    ports:
    - 8081:8080
    - 1323:1323
    environment:
    - WEBAPP_SECRET=treehugger
volumes:
  db_data:
