version: '3.6'
#sudo docker run -p 8081:8080 -v /home/ubuntu/enroute/enroute-cp:/hasura-migrations -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@postgres:5432/postgres hasura/graphql-engine:v1.0.0-beta.4.cli-migrations
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.4.cli-migrations
    volumes:
    - ./:/hasura-migrations
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations/migrations
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
